[package]
edition = "2021"
name = "dts"
version = "0.1.0"

[workspace]
members = [
    "crates/dts-core",
    "crates/dts-json",
    "crates/hcl",
]

[features]
default = ["color"]
color = ["bat", "bat/paging", "clap/color", "once_cell"]

[dependencies]
anyhow = "1.0.44"
atty = "0.2.14"
clap_generate = "= 3.0.0-rc.7"
dts-core = { path = "crates/dts-core" }
dts-json = { path = "crates/dts-json" }
grep-cli = "0.1.6"
indoc = "1.0"
rayon = "1.5.1"
regex = "1.5.4"
shell-words = "1.0.0"
termcolor = "1.1.2"
textwrap = "0.14.2"
unescape = "0.1.0"

[dependencies.bat]
optional = true
default-features = false
features = ["regex-onig"]
version = "0.18.3"

[dependencies.clap]
default-features = false
features = ["std", "derive", "env", "suggestions"]
version = "= 3.0.0-rc.7"

[dependencies.once_cell]
optional = true
version = "1.9.0"

[dev-dependencies]
assert_cmd = "2.0.2"
criterion = "0.3"
hcl = { path = "crates/hcl" }
pretty_assertions = "1.0.0"
predicates = "2.0.3"
temp-env = "0.2.0"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
bench = false
path = "crates/dts/main.rs"
name = "dts"

[[test]]
name = "integration"
path = "tests/integration_tests.rs"
