[package]
name = "dts"
version = "0.2.7"
authors = ["Martin Ohmann <martinohmann@gmail.com>"]
license = "MIT"
description = "A tool to deserialize, transform and serialize data between different encodings"
repository = "https://github.com/martinohmann/dts"
documentation = "https://docs.rs/dts/"
keywords = ["hcl", "json", "yaml", "jq"]
categories = ["encoding"]
readme = "README.md"
edition = "2021"
exclude = [
    ".github/",
]

[workspace]
members = [
    "crates/dts-core",
]

[features]
default = ["color"]
color = ["bat", "bat/paging", "clap/color"]

[dependencies]
anyhow = "1.0.57"
atty = "0.2.14"
clap_generate = "= 3.0.0-rc.7"
dts-core = { path = "crates/dts-core", version = "0.2.6" }
grep-cli = "0.1.6"
rayon = "1.5.3"
regex = "1.5.6"
shell-words = "1.1.0"
termcolor = "1.1.3"
unescape = "0.1.0"

[dependencies.bat]
optional = true
default-features = false
features = ["regex-onig"]
version = "0.21.0"

[dependencies.clap]
default-features = false
features = ["std", "derive", "env", "suggestions"]
version = "= 3.0.0-rc.7"

[dependencies.serde_json]
features = ["preserve_order"]
version = "1.0.81"

[dev-dependencies]
assert_cmd = "2.0.4"
criterion = "0.3"
pretty_assertions = "1.2.1"
predicates = "2.1.1"
temp-env = "0.2.0"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
bench = false
path = "crates/dts/main.rs"
name = "dts"

[[test]]
name = "integration"
path = "tests/integration_tests.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
