[package]
edition = "2021"
name = "dts"
version = "0.1.0"

[dependencies]
anyhow = "1.0.44"
atty = "0.2.14"
clap = "3.0.0-beta.5"
crossbeam-channel = "0.5.1"
crossbeam-utils = "0.8.5"
csv = "1.1.6"
deser-hjson = "1.0.2"
json5 = "0.4.1"
jsonpath-rust = "0.1.3"
regex = "1.5.4"
ron = "0.7.0"
serde-pickle = "1.1.0"
serde-xml-rs = "0.5.1"
serde_qs = "0.8.5"
serde_yaml = "0.8.21"
thiserror = "1.0.30"
toml = "0.5.8"
unescape = "0.1.0"
ureq = "2.3.0"
url = "2.2.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"

[dependencies.serde_json]
features = ["preserve_order"]
version = "1.0.68"

[dev-dependencies]
assert_cmd = "2.0.2"
pretty_assertions = "1.0.0"
tempfile = "3.2.0"
