[package]
name = "trnscd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
clap = "3.0.0-beta.5"
csv = "1.1.6"
deser-hjson = "1.0.2"
json5 = "0.4.1"
ron = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"
toml = "0.5.8"

[features]
