[package]
edition = "2021"
name = "dts"
version = "0.1.0"

[workspace]
members = [
    "crates/dts-core",
    "crates/hcl",
]

[dependencies]
anyhow = "1.0.44"
atty = "0.2.14"
clap_generate = "= 3.0.0-rc.7"
dts-core = { path = "crates/dts-core" }
rayon = "1.5.1"
regex = "1.5.4"
unescape = "0.1.0"

[dependencies.clap]
features = ["derive"]
version = "= 3.0.0-rc.7"

[dev-dependencies]
assert_cmd = "2.0.2"
criterion = "0.3"
hcl = { path = "crates/hcl" }
pretty_assertions = "1.0.0"
predicates = "2.0.3"

[dev-dependencies.serde_json]
features = ["preserve_order"]
version = "1.0.68"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
bench = false
path = "crates/dts/main.rs"
name = "dts"

[[test]]
name = "integration"
path = "tests/integration_tests.rs"
