[package]
name = "hcl"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"

[dependencies.indexmap]
features = ["serde"]
version = "1.7.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"

[dev-dependencies]
pretty_assertions = "1.0.0"

[dev-dependencies.serde_json]
features = ["preserve_order"]
version = "1.0.68"
