---
name: deploy
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-20.04
            use-cross: true
          - target: arm-unknown-linux-gnueabihf
            os: ubuntu-20.04
            use-cross: true
          - target: arm-unknown-linux-musleabihf
            os: ubuntu-20.04
            use-cross: true
          - target: x86_64-apple-darwin
            os: macos-10.15
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04
            use-cross: true
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install prerequisites
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            arm-unknown-linux-*)
              sudo apt-get -y update
              sudo apt-get -y install gcc-arm-linux-gnueabihf ;;
            aarch64-unknown-linux-gnu)
              sudo apt-get -y update
              sudo apt-get -y install gcc-aarch64-linux-gnu ;;
          esac

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal

      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --locked --release --target=${{ matrix.job.target }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        if: ${{ matrix.job.use-cross != true }}
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: test
          args: --locked --target=${{ matrix.job.target }}

      - name: Strip debug information from executable
        id: strip
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            arm-unknown-linux-*)
              STRIP=arm-linux-gnueabihf-strip ;;
            aarch64-unknown-linux-gnu)
              STRIP=aarch64-linux-gnu-strip ;;
            *)
              STRIP=strip ;;
          esac

          # Setup paths
          BIN_DIR="release-artifacts/"

          mkdir -p "$BIN_DIR"

          BIN_PATH="${BIN_DIR}/dts"

          # Copy the release build binary to the result location
          cp "target/${{ matrix.job.target }}/release/${BIN_NAME}" "$BIN_DIR"

          "$STRIP" "$BIN_PATH"

          echo ::set-output name=BIN_PATH::${BIN_PATH}

      - name: Create tarball
        id: package
        shell: bash
        run: |
          PKG_BASENAME="dts-v${PROJECT_VERSION}-${{ matrix.job.target }}"
          PKG_NAME="${PKG_BASENAME}.tar.gz"

          echo ::set-output name=PKG_NAME::${PKG_NAME}

          PKG_STAGING="release-artifacts/package"
          ARCHIVE_DIR="${PKG_STAGING}/${PKG_BASENAME}/"

          mkdir -p "$ARCHIVE_DIR"

          # Binary
          cp "${{ steps.strip.outputs.BIN_PATH }}" "$ARCHIVE_DIR"

          # README, LICENSE and CHANGELOG files
          cp "README.md" "LICENSE" "CHANGELOG.md" "$ARCHIVE_DIR"

          # base compressed package
          pushd "${PKG_STAGING}/" >/dev/null

          tar czf "$PKG_NAME" "$PKG_BASENAME"/*

          popd >/dev/null

          echo ::set-output name=PKG_PATH::"${PKG_STAGING}/${PKG_NAME}"
