---
name: publish-crates
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish-crates:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Login to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo login ${CARGO_REGISTRY_TOKEN}

      - name: Publish crates
        run: |
          cargo publish --package dts-core || true
          cargo publish --package dts || true
